### ISSUE TITLE
[FEAT] 인증하기 UI 구현

### ISSUE THREAD

**Issue by noah0316** [29th-SOPKATHON-DLink/Client-iOS#3]
## 📝 To-do

- [ ] 키보드 관련 기능 구현
- [ ] 오늘 우리가 마신 술은? UI 구현
- [ ] 오늘 모임은 어땠나요? UI 구현
